name:                css

description:         Please see the README on GitHub at <https://github.com/githubuser/css#readme>

dependencies:
- base >= 4.7 && < 5
- clay
- text

ghc-options:
- -Wall

library:
    source-dirs: src

executables:
    css-generator:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -O0
        dependencies:
        - css
